/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CartItem {
        "name": string;
        "price": number;
        "qty": number;
        "size": string;
        "skuId": string;
        "thumbnail": string;
    }
    interface CartList {
        "cartItems": string;
    }
    interface ItemPrice {
        "minimal": boolean;
        "totalPrice": string;
        "unitPrice": string;
    }
    interface ItemQty {
        "qty": number;
        "readonly": boolean;
    }
}
declare global {
    interface HTMLCartItemElement extends Components.CartItem, HTMLStencilElement {
    }
    var HTMLCartItemElement: {
        prototype: HTMLCartItemElement;
        new (): HTMLCartItemElement;
    };
    interface HTMLCartListElement extends Components.CartList, HTMLStencilElement {
    }
    var HTMLCartListElement: {
        prototype: HTMLCartListElement;
        new (): HTMLCartListElement;
    };
    interface HTMLItemPriceElement extends Components.ItemPrice, HTMLStencilElement {
    }
    var HTMLItemPriceElement: {
        prototype: HTMLItemPriceElement;
        new (): HTMLItemPriceElement;
    };
    interface HTMLItemQtyElement extends Components.ItemQty, HTMLStencilElement {
    }
    var HTMLItemQtyElement: {
        prototype: HTMLItemQtyElement;
        new (): HTMLItemQtyElement;
    };
    interface HTMLElementTagNameMap {
        "cart-item": HTMLCartItemElement;
        "cart-list": HTMLCartListElement;
        "item-price": HTMLItemPriceElement;
        "item-qty": HTMLItemQtyElement;
    }
}
declare namespace LocalJSX {
    interface CartItem {
        "name"?: string;
        "price"?: number;
        "qty"?: number;
        "size"?: string;
        "skuId"?: string;
        "thumbnail"?: string;
    }
    interface CartList {
        "cartItems"?: string;
    }
    interface ItemPrice {
        "minimal"?: boolean;
        "totalPrice"?: string;
        "unitPrice"?: string;
    }
    interface ItemQty {
        "qty"?: number;
        "readonly"?: boolean;
    }
    interface IntrinsicElements {
        "cart-item": CartItem;
        "cart-list": CartList;
        "item-price": ItemPrice;
        "item-qty": ItemQty;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cart-item": LocalJSX.CartItem & JSXBase.HTMLAttributes<HTMLCartItemElement>;
            "cart-list": LocalJSX.CartList & JSXBase.HTMLAttributes<HTMLCartListElement>;
            "item-price": LocalJSX.ItemPrice & JSXBase.HTMLAttributes<HTMLItemPriceElement>;
            "item-qty": LocalJSX.ItemQty & JSXBase.HTMLAttributes<HTMLItemQtyElement>;
        }
    }
}
